from ..contracts import DataKind, DomainPack, TaskKind, ToolContract


BATTERY_PACK = DomainPack(
    key="battery",
    title="EV Battery Pack Diagnostics",
    data_kind=DataKind.BATTERY_PACK,
    tasks=(TaskKind.ANOMALY_LOCALIZATION, TaskKind.FAULT_DIAGNOSIS, TaskKind.PROGNOSIS),
    required_metadata=("cell_ids", "timestamps"),
    optional_metadata=("pack_current", "operating_state", "ambient_temperature", "capacity_history"),
    tools=(
        ToolContract(
            "battery_data_quality",
            "Validate cell voltage/temperature telemetry and channel alignment.",
            ("cell_voltage", "cell_temperature", "timestamps"),
            outputs=("quality_flags", "missingness", "sensor_outliers"),
            evidence_fields=("quality_flags",),
        ),
        ToolContract(
            "operating_state_segmentation",
            "Separate charging, discharging and rest because normal behavior differs by state.",
            ("timestamps",),
            optional_inputs=("pack_current", "operating_state"),
            outputs=("state_labels", "state_intervals"),
            evidence_fields=("state_intervals",),
        ),
        ToolContract(
            "cell_deviation_features",
            "Measure each cell relative to robust pack-level voltage/temperature baselines.",
            ("cell_voltage", "cell_temperature"),
            outputs=("delta_voltage", "delta_temperature", "imbalance_scores"),
            evidence_fields=("imbalance_scores",),
        ),
        ToolContract(
            "battery_temporal_features",
            "Measure derivatives, trends and rolling variability of cells and pack signals.",
            ("cell_voltage", "cell_temperature", "timestamps"),
            optional_inputs=("pack_current",),
            outputs=("dv_dt", "dt_dt", "rolling_trends", "temporal_features"),
            evidence_fields=("rolling_trends",),
        ),
        ToolContract(
            "cell_spatial_consistency",
            "Detect cells whose behavior diverges from correlated neighbors/the pack population.",
            ("cell_voltage", "cell_temperature", "cell_ids"),
            outputs=("cell_similarity", "spatial_anomaly_scores"),
            evidence_fields=("spatial_anomaly_scores",),
        ),
        ToolContract(
            "adaptive_window_builder",
            "Construct multiple temporal windows for near-term and longer-horizon diagnosis/prognosis.",
            ("timestamps", "state_labels"),
            optional_inputs=("window_horizons",),
            outputs=("windows", "window_metadata"),
        ),
        ToolContract(
            "battery_spatiotemporal_model",
            "Fuse cell-to-cell structure with temporal evolution for anomaly/fault scoring.",
            ("windows", "temporal_features", "spatial_anomaly_scores"),
            optional_inputs=("trained_predictor",),
            outputs=("cell_fault_scores", "pack_fault_score", "latent_health_state"),
            evidence_fields=("cell_fault_scores",),
        ),
        ToolContract(
            "battery_anomaly_localization",
            "Rank abnormal cells and fault signatures from multiscale evidence.",
            ("cell_fault_scores", "imbalance_scores"),
            outputs=("ranked_cells", "fault_hypotheses", "confidence"),
            evidence_fields=("ranked_cells", "fault_hypotheses"),
        ),
        ToolContract(
            "battery_failure_prognosis",
            "Estimate probability of future failure within configured horizons.",
            ("latent_health_state", "windows"),
            optional_inputs=("capacity_history", "trained_prognostic_model"),
            outputs=("failure_probability_by_horizon", "uncertainty"),
            evidence_fields=("failure_probability_by_horizon", "uncertainty"),
        ),
        ToolContract(
            "battery_decision",
            "Produce localized diagnosis/prognosis or abstain when cell evidence is ambiguous.",
            ("ranked_cells", "failure_probability_by_horizon"),
            outputs=("condition", "affected_cells", "risk", "confidence", "abstain_reason"),
            evidence_fields=("affected_cells", "risk"),
        ),
    ),
    outputs=("condition", "affected_cells", "fault_type", "failure_risk", "horizon", "confidence", "evidence"),
    benchmark_targets=("cell_localization_f1", "fault_accuracy", "AUROC", "AUPRC", "prognosis_brier_score"),
)
