from ..contracts import DataKind, DomainPack, TaskKind, ToolContract


BEARING_PACK = DomainPack(
    key="bearing",
    title="Rotating Machinery / Bearing Diagnostics",
    data_kind=DataKind.WAVEFORM,
    tasks=(TaskKind.FAULT_DIAGNOSIS, TaskKind.CONDITION_MONITORING),
    required_metadata=("sampling_rate_hz",),
    optional_metadata=("shaft_rate_hz", "load", "BPFO", "BPFI", "BSF", "FTF"),
    tools=(
        ToolContract(
            "signal_integrity",
            "Validate waveform quality and sampling adequacy.",
            ("signal", "sampling_rate_hz"),
            outputs=("quality_flags", "duration_s", "clipping_fraction", "dc_offset"),
            evidence_fields=("quality_flags",),
            failure_modes=("nan_or_inf", "too_short", "severe_clipping"),
        ),
        ToolContract(
            "time_domain_features",
            "Measure amplitude and impulsiveness indicators.",
            ("signal",),
            outputs=("rms", "std", "peak", "crest_factor", "skewness", "kurtosis"),
            evidence_fields=("rms", "crest_factor", "kurtosis"),
            implementation="SignalProcessingAgent",
        ),
        ToolContract(
            "welch_psd",
            "Estimate stable spectral energy and dominant resonance regions.",
            ("signal", "sampling_rate_hz"),
            outputs=("frequency_hz", "psd", "dominant_peaks"),
            evidence_fields=("dominant_peaks",),
            implementation="SignalProcessingAgent",
        ),
        ToolContract(
            "time_frequency_analysis",
            "Detect non-stationary and transient spectral behavior with STFT/CWT-like analysis.",
            ("signal", "sampling_rate_hz"),
            outputs=("time_axis", "frequency_axis", "time_frequency_map", "transient_regions"),
            evidence_fields=("transient_regions",),
        ),
        ToolContract(
            "spectral_kurtosis",
            "Rank resonance bands by impulsive/transient content.",
            ("signal", "sampling_rate_hz"),
            outputs=("band_scores", "recommended_band_hz"),
            evidence_fields=("recommended_band_hz", "band_scores"),
        ),
        ToolContract(
            "bandpass_filter",
            "Isolate the resonance band selected by transient analysis.",
            ("signal", "sampling_rate_hz", "band_hz"),
            outputs=("filtered_signal", "filter_metadata"),
            preconditions=("0 < low_hz < high_hz < Nyquist",),
            evidence_fields=("filter_metadata",),
            implementation="BearingDiagnosticAgent",
        ),
        ToolContract(
            "hilbert_envelope",
            "Demodulate repetitive impacts from the selected resonance band.",
            ("filtered_signal",),
            outputs=("envelope",),
            implementation="BearingDiagnosticAgent",
        ),
        ToolContract(
            "envelope_spectrum",
            "Expose repetition frequencies of bearing impacts.",
            ("envelope", "sampling_rate_hz"),
            outputs=("frequency_hz", "envelope_power", "peaks"),
            evidence_fields=("peaks",),
            implementation="BearingDiagnosticAgent",
        ),
        ToolContract(
            "bearing_frequency_match",
            "Match envelope peaks to BPFO/BPFI/BSF/FTF harmonics and sidebands.",
            ("frequency_hz", "envelope_power", "fault_frequencies"),
            optional_inputs=("shaft_rate_hz",),
            outputs=("fault_ranking", "harmonic_matches", "sideband_matches"),
            evidence_fields=("harmonic_matches", "sideband_matches"),
            implementation="BearingDiagnosticAgent",
        ),
        ToolContract(
            "bearing_evidence_fusion",
            "Combine impulsiveness, resonance, and characteristic-frequency evidence into diagnosis/abstention.",
            ("time_features", "fault_ranking"),
            optional_inputs=("transient_band", "operating_condition"),
            outputs=("label", "confidence", "severity", "abstain_reason"),
            evidence_fields=("label", "confidence", "severity"),
        ),
    ),
    outputs=("condition", "fault_location", "severity", "confidence", "evidence", "tool_trace"),
    benchmark_targets=("accuracy", "macro_f1", "abstention_rate", "cross_load_accuracy", "cross_speed_accuracy"),
)
