from ..contracts import DataKind, DomainPack, TaskKind, ToolContract


PROCESS_PACK = DomainPack(
    key="process",
    title="Chemical / Process Plant Diagnostics",
    data_kind=DataKind.MULTIVARIATE_SERIES,
    tasks=(TaskKind.CONDITION_MONITORING, TaskKind.ROOT_CAUSE, TaskKind.FAULT_DIAGNOSIS),
    required_metadata=("channel_names", "sampling_rate_hz", "normal_reference"),
    optional_metadata=("process_topology", "operating_mode", "fault_catalog", "timestamps"),
    tools=(
        ToolContract(
            "process_data_quality",
            "Check missingness, constant sensors, scaling and synchronization.",
            ("signal_matrix", "channel_names"),
            outputs=("quality_flags", "channel_statistics"),
            evidence_fields=("quality_flags",),
            implementation="tsdiag.tools.data_quality_check",
        ),
        ToolContract(
            "standardize_against_normal",
            "Normalize current and healthy-reference data using healthy-reference statistics.",
            ("signal_matrix", "normal_reference"),
            outputs=("standardized_signal", "standardized_reference", "reference_mean", "reference_scale"),
            preconditions=("reference and current channels must align",),
            implementation="tsdiag.tools.standardize_against_normal",
        ),
        ToolContract(
            "pca_monitoring",
            "Model the healthy process subspace and compute T2/SPE-style deviations.",
            ("standardized_signal", "standardized_reference"),
            outputs=("scores", "t2", "spe", "control_limits", "alarm_mask", "pca_state"),
            evidence_fields=("t2", "spe", "control_limits"),
            implementation="tsdiag.tools.pca_monitoring",
        ),
        ToolContract(
            "contribution_analysis",
            "Rank variables contributing most to the current process alarm.",
            ("standardized_signal", "pca_state", "alarm_mask"),
            outputs=("variable_contributions", "suspect_variables", "ranked_indices"),
            evidence_fields=("suspect_variables", "variable_contributions"),
            implementation="tsdiag.tools.contribution_analysis",
        ),
        ToolContract(
            "pre_post_shift_evidence",
            "Measure per-variable pre/post-alarm distribution shift evidence.",
            ("standardized_signal", "channel_names", "alarm_mask"),
            outputs=("shift_scores", "shift_details"),
            evidence_fields=("shift_scores",),
            implementation="tsdiag.tools.pre_post_shift_evidence",
        ),
        ToolContract(
            "temporal_fault_type_evidence",
            "Extract temporal signatures useful for distinguishing process fault types.",
            ("standardized_signal", "channel_names", "alarm_mask"),
            outputs=("fault_type_scores", "channel_temporal_features"),
            evidence_fields=("fault_type_scores",),
            implementation="tsdiag.tools.temporal_fault_type_evidence",
        ),
        ToolContract(
            "stationarity_analysis",
            "Evaluate stationarity and prepare the causal-analysis signal using the same differencing rule as the baseline runner.",
            ("standardized_signal",),
            outputs=("stationarity_flags", "differencing_recommendations", "causal_signal", "differenced_channels"),
            evidence_fields=("stationarity_flags",),
            implementation="tsdiag.tools.stationarity_analysis",
        ),
        ToolContract(
            "granger_causality",
            "Screen directed predictive relationships among synchronized variables.",
            ("causal_signal", "channel_names"),
            outputs=("directed_edges", "p_values"),
            evidence_fields=("directed_edges",),
            failure_modes=("insufficient_samples", "nonstationary_input", "singular_model"),
            implementation="tsdiag.tools.granger_causality",
        ),
        ToolContract(
            "causal_graph_filter",
            "Constrain predictive links using process topology/physics when available.",
            ("directed_edges",),
            optional_inputs=("process_topology",),
            outputs=("filtered_causal_graph", "removed_edges"),
            evidence_fields=("filtered_causal_graph",),
            implementation="tsdiag.tools.causal_graph_filter",
        ),
        ToolContract(
            "fault_onset_timing",
            "Estimate when each affected variable first became abnormal.",
            ("standardized_signal", "alarm_mask", "channel_names"),
            optional_inputs=("timestamps",),
            outputs=("onset_times", "onset_timestamps", "onset_order", "onset_details", "baseline", "channel_alarm_mask", "z_scores"),
            evidence_fields=("onset_order",),
            implementation="tsdiag.tools.fault_onset_timing",
        ),
        ToolContract(
            "root_cause_rank",
            "Combine contribution, shift, causality and onset evidence to rank root-cause variables.",
            ("suspect_variables", "filtered_causal_graph", "onset_order", "variable_contributions", "shift_scores", "channel_names"),
            outputs=("root_cause_ranking", "propagation_paths", "confidence"),
            evidence_fields=("root_cause_ranking", "propagation_paths"),
            implementation="tsdiag.tools.root_cause_rank_enhanced",
        ),
        ToolContract(
            "process_diagnosis",
            "Convert the fixed baseline evidence into diagnosis or abstention.",
            ("root_cause_ranking", "propagation_paths"),
            optional_inputs=("fault_catalog", "shift_scores", "variable_contributions", "onset_order", "fault_type_scores", "channel_names"),
            outputs=("fault_label", "root_cause", "confidence", "abstain_reason", "affected_variables", "propagation_paths"),
            evidence_fields=("root_cause", "propagation_paths"),
            implementation="tsdiag.tools.process_diagnosis",
        ),
    ),
    outputs=("fault_detected", "fault_label", "root_cause", "affected_variables", "propagation_path", "confidence", "evidence"),
    benchmark_targets=("detection_f1", "root_cause_accuracy", "fault_class_accuracy", "false_alarm_rate", "detection_delay"),
)
