from ..contracts import DataKind, DomainPack, TaskKind, ToolContract


TURBOFAN_PACK = DomainPack(
    key="turbofan",
    title="Aircraft Turbofan / Run-to-Failure Prognostics",
    data_kind=DataKind.RUN_TO_FAILURE,
    tasks=(TaskKind.CONDITION_MONITORING, TaskKind.PROGNOSIS, TaskKind.RUL),
    required_metadata=("channel_names", "cycle_index"),
    optional_metadata=("operating_conditions", "engine_id", "failure_threshold", "trained_rul_model"),
    tools=(
        ToolContract(
            "sensor_screening",
            "Remove uninformative/noisy channels using variance, monotonicity and trend relevance.",
            ("signal_matrix", "channel_names", "cycle_index"),
            outputs=("selected_channels", "sensor_scores", "rejected_channels"),
            evidence_fields=("selected_channels", "sensor_scores"),
        ),
        ToolContract(
            "operating_condition_identification",
            "Identify engine operating regimes that should not be conflated with degradation.",
            ("signal_matrix",),
            optional_inputs=("operating_conditions",),
            outputs=("regime_ids", "regime_statistics"),
            evidence_fields=("regime_statistics",),
        ),
        ToolContract(
            "regime_normalization",
            "Normalize sensor trajectories within comparable operating regimes.",
            ("signal_matrix", "regime_ids", "selected_channels"),
            outputs=("normalized_signal", "normalization_state"),
        ),
        ToolContract(
            "degradation_smoothing",
            "Separate long-term degradation trend from short-term sensor fluctuations.",
            ("normalized_signal", "cycle_index"),
            optional_inputs=("smoothing_method",),
            outputs=("trend_signal", "residual_signal"),
            evidence_fields=("trend_signal",),
        ),
        ToolContract(
            "sequence_windowing",
            "Create fixed-length temporal windows for prognostic models.",
            ("normalized_signal", "cycle_index"),
            optional_inputs=("window_length", "stride"),
            outputs=("sequence_windows", "window_end_cycles"),
        ),
        ToolContract(
            "health_index_estimation",
            "Construct an interpretable or learned scalar degradation representation.",
            ("trend_signal",),
            optional_inputs=("health_index_model",),
            outputs=("health_index", "health_contributors"),
            evidence_fields=("health_index", "health_contributors"),
        ),
        ToolContract(
            "rul_prediction",
            "Predict remaining useful life from current degradation history.",
            ("sequence_windows",),
            optional_inputs=("trained_rul_model", "health_index"),
            outputs=("rul_cycles", "prediction_metadata"),
            evidence_fields=("rul_cycles",),
            implementation="PrognosticsAgent",
        ),
        ToolContract(
            "rul_uncertainty",
            "Quantify uncertainty around the remaining-life estimate.",
            ("rul_cycles",),
            optional_inputs=("ensemble_predictions", "residual_calibration"),
            outputs=("rul_interval", "uncertainty_score"),
            evidence_fields=("rul_interval", "uncertainty_score"),
        ),
        ToolContract(
            "prognostic_explanation",
            "Identify sensors and degradation trends driving the RUL estimate.",
            ("health_contributors", "rul_cycles"),
            optional_inputs=("model_attributions",),
            outputs=("critical_sensors", "explanation"),
            evidence_fields=("critical_sensors",),
        ),
        ToolContract(
            "turbofan_decision",
            "Return health state/RUL or abstain when degradation evidence is outside model support.",
            ("rul_cycles", "rul_interval", "critical_sensors"),
            optional_inputs=("domain_shift_score",),
            outputs=("health_state", "rul_cycles", "confidence", "abstain_reason"),
            evidence_fields=("health_state", "rul_cycles", "critical_sensors"),
        ),
    ),
    outputs=("health_state", "rul_cycles", "rul_interval", "confidence", "critical_sensors", "evidence"),
    benchmark_targets=("RMSE", "MAE", "PHM_score", "interval_coverage", "calibration_error"),
)
