from ..contracts import DataKind, DomainPack, TaskKind, ToolContract


WIND_SCADA_PACK = DomainPack(
    key="wind_scada",
    title="Wind Turbine / SCADA Condition Monitoring",
    data_kind=DataKind.SCADA,
    tasks=(TaskKind.CONDITION_MONITORING, TaskKind.ROOT_CAUSE, TaskKind.PROGNOSIS),
    required_metadata=("channel_names", "timestamps"),
    optional_metadata=("ambient_conditions", "operating_regime_labels", "maintenance_history", "physics_model"),
    tools=(
        ToolContract(
            "scada_quality_check",
            "Validate telemetry continuity, missingness, timestamps and sensor plausibility.",
            ("signal_matrix", "channel_names", "timestamps"),
            outputs=("quality_flags", "missingness", "sampling_irregularity"),
            evidence_fields=("quality_flags",),
        ),
        ToolContract(
            "operating_regime_detection",
            "Partition telemetry into comparable operating conditions before anomaly scoring.",
            ("signal_matrix", "channel_names"),
            optional_inputs=("operating_regime_labels",),
            outputs=("regime_ids", "regime_descriptions"),
            evidence_fields=("regime_descriptions",),
        ),
        ToolContract(
            "normal_behavior_model",
            "Estimate expected sensor values conditioned on operating regime and ambient variables.",
            ("signal_matrix", "regime_ids"),
            optional_inputs=("normal_reference", "physics_model", "ambient_conditions"),
            outputs=("expected_signal", "model_uncertainty"),
            evidence_fields=("model_uncertainty",),
        ),
        ToolContract(
            "residual_analysis",
            "Compute observed-minus-expected residuals for monitored channels.",
            ("signal_matrix", "expected_signal"),
            outputs=("residuals", "normalized_residuals"),
            evidence_fields=("normalized_residuals",),
        ),
        ToolContract(
            "rolling_statistics",
            "Track persistent shifts in mean, variance and slope instead of isolated spikes.",
            ("residuals", "timestamps"),
            outputs=("rolling_mean", "rolling_std", "rolling_slope"),
            evidence_fields=("rolling_mean", "rolling_slope"),
        ),
        ToolContract(
            "cross_sensor_relationships",
            "Monitor physically related sensor pairs for correlation/relationship drift.",
            ("signal_matrix", "channel_names"),
            optional_inputs=("relationship_pairs",),
            outputs=("correlations", "relationship_shift_scores"),
            evidence_fields=("relationship_shift_scores",),
        ),
        ToolContract(
            "scada_anomaly_detection",
            "Flag persistent multivariate residual anomalies within operating regime.",
            ("normalized_residuals",),
            optional_inputs=("normal_reference",),
            outputs=("anomaly_scores", "alarm_mask"),
            evidence_fields=("anomaly_scores", "alarm_mask"),
        ),
        ToolContract(
            "change_point_detection",
            "Detect sustained regime-independent degradation shifts while accounting for heteroscedastic residual noise.",
            ("residuals", "timestamps"),
            optional_inputs=("regime_ids", "variance_model"),
            outputs=("change_points", "change_magnitudes"),
            evidence_fields=("change_points", "change_magnitudes"),
        ),
        ToolContract(
            "physics_consistency_check",
            "Verify anomaly hypotheses against turbine physics and operating constraints.",
            ("candidate_anomalies",),
            optional_inputs=("physics_model", "operating_regime", "ambient_conditions"),
            outputs=("verification_findings",),
            evidence_fields=("verification_findings",),
        ),
        ToolContract(
            "scada_risk_assessment",
            "Aggregate persistence, residual magnitude, relationship drift and physics checks into subsystem risk.",
            ("anomaly_scores", "change_points", "verification_findings"),
            optional_inputs=("maintenance_history",),
            outputs=("subsystem", "risk_level", "confidence", "warning_horizon", "abstain_reason"),
            evidence_fields=("subsystem", "risk_level", "warning_horizon"),
        ),
    ),
    outputs=("subsystem", "condition", "risk_level", "warning_horizon", "confidence", "evidence", "tool_trace"),
    benchmark_targets=("event_recall", "false_alarm_rate", "lead_time", "subsystem_accuracy", "calibration_error"),
)
